### PR TITLE
fix Class 'Twig_Extensions_Slim' not found

### PR DESCRIPTION
**Pull request by fayland**
I'm keep getting

PHP Fatal error:  Class 'Twig_Extensions_Slim' not found in web/vendor/slim/extras/Slim/Extras/Views/Twig.php on line 133

which dues to

```
        // Check for Composer Package Autoloader class loading
        if (!class_exists('\Twig_Extensions_Autoloader')) {
            $extension_autoloader = dirname(__FILE__) . '/Extension/TwigAutoloader.php';
            if (file_exists($extension_autoloader)) require_once $extension_autoloader;
        }
```

already loaded vendor/twig/extensions/lib/Twig/Extensions/Autoloader.php
so the vendor/slim/extras/Slim/Extras/Views/Extension/TwigAutoloader.php is not loaded at all.

the fixes force to load vendor/slim/extras/Slim/Extras/Views/Extension/TwigAutoloader.php always (do not check class_exists).

newbie to php and hope it's fine.

Thanks

### CODE REVIEW

**Comment by silentworks** [comment]
Is it me or does your pull request look like you removed 1 line and added it back again? Also please send pull requests to develop branch, make changes only on develop branch.

**Comment by fayland** [comment]
I just commented it out. Thanks

**Comment by silentworks** [comment]
I will need to investigate this a bit more before merging it in.

**Comment by arnauvp** [comment]
+1 to this (or any better fix that resolves the issue).
I'm also finding this conflict between Slim Extras and Twig Extensions.

**Comment by malenkiki** [comment]
+1, I have the same issue. I hope this can be solve very soon…

**Comment by arnauvp** [comment]
hello @silentworks! Any news regarding this? Are we missing anything?

**Comment by jasteralan** [comment]
maybe the autoload doesn't work well ?? try sue this composer.json to install   

```
"require": {  
    "slim/slim": "*",  
    "slim/extras": "*",  
    "twig/twig": "*",  
}  
```

I work fine with this setting

**Comment by arnauvp** [comment]
I'm afraid not, as the conflict is with twig/extensions and slim/extras.
This is what I use:

``` json
"require": {  
        "slim/slim": "2.*",
        "slim/extras": "2.*",
        "twig/twig": "1.*",
        "twig/extensions": "dev-master"
}
```

but using \* didn't change the error.

**Comment by silentworks** [comment]
We are now recommending [Slim Views](https://github.com/codeguy/Slim-Views) instead of the views in Slim Extras where this has been fixed. This way you won't be required to download all the Slim Extras repo just to use the Views. I will add a note to this about the change.

**Pull request closed without merging**
