### PR TITLE
Update Views/Extension/Twig/Extensions/Slim.php

### PR DESCRIPTION
**Pull request by ilmala**
When install with composer the Slim class not find.
Fix with use \Slim\Slim in head

### CODE REVIEW

**Comment by silentworks** [comment]
This is not necessary since we are already calling Slim namespaced.

**Comment by ilmala** [comment]
yes but the skeleton not use namespace but  \Slim\Slim

**Comment by silentworks** [comment]
We have tested this and it currently work as is, can you paste a gist of your index.php code, I am thinking you probably have something setup wrong in there.

**Comment by ilmala** [comment]
<?php
require '../vendor/autoload.php';

use \Slim\Extras\Views\Twig;
use \Slim\Slim;
use \Slim\Extras\Log\DateTimeFileWriter;

// Prepare app
$app = new Slim(array(
    'templates.path' => '../templates',
    'log.level' => 4,
    'log.enabled' => true,
    'log.writer' => new DateTimeFileWriter(array(
        'path' => '../logs',
        'name_format' => 'y-m-d.log'
    ))
));

// Prepare view
Twig::$twigOptions = array(
    'charset' => 'utf-8',
    'cache' => realpath('../templates/cache'),
    'auto_reload' => true,
    'strict_variables' => false,
    'autoescape' => true
);
// Set Extensions
Twig::$twigExtensions = array(
    'Twig_Extensions_Slim',
);
$app->view(new Twig());

// Define routes
$app->get('/', function () use ($app) {
    $app->render('index.html.twig');
})->name('home');

// Run app
$app->run();

i have this error
Fatal error: Class 'Slim' not found in D:\wamp\www\xagena_php_v4\vendor\slim\extras\Slim\Extras\Views\Extension\Twig\Extensions\Slim.php on line 21

**Comment by silentworks** [comment]
You might want to switch this around:

``` php
use \Slim\Extras\Views\Twig;
use \Slim\Slim;
use \Slim\Extras\Log\DateTimeFileWriter;
```

to this:

``` php
use \Slim\Slim;
use \Slim\Extras\Views\Twig;
use \Slim\Extras\Log\DateTimeFileWriter;
```

Notice the use of Slim before the Twig View.

This was addressed in this post http://help.slimframework.com/discussions/problems/943-cant-get-twig-extensions-to-work

**Comment by ilmala** [comment]
sorry same error

**Comment by silentworks** [comment]
Can you paste your composer namespace file, which contains the classes that gets loaded. I think the order might be wrong in it.

**Comment by ilmala** [comment]
``` php
return array(
    'Twig_Extensions_' => $vendorDir . '/slim/extras/Views/Extension/',
    'Twig_' => $vendorDir . '/twig/twig/lib/',
    'Slim\\Extras' => $vendorDir . '/slim/extras/.',
    'Slim' => $vendorDir . '/slim/slim/.',
);
```

**Comment by silentworks** [comment]
I have just tested everything you pasted and it works fine for me, my namespace file has the same order as yours. I think you have something else wrong in your code. Is your codebase available on Github or something so I could take a look at it?

**Comment by ilmala** [comment]
look here
https://github.com/ilmala/TestSlimAndPropel

**Comment by silentworks** [comment]
Ok the problem is you are using extras 2.*, we haven't updated that as yet, you would need to use extras dev-develop for now. I will so a new release this weekend for 2.0.1.

**Comment by ilmala** [comment]
ok thanks for all
is not a big problem, for now my solution is fine in my project.

have a nice day/night

**Comment by silentworks** [comment]
Ok I just pushed new code for 2.0.1, so if you do a composer update, you should get the latest working code.

**Pull request closed without merging**
