### PR TITLE
Twig view tweaks

### PR DESCRIPTION
**Pull request by richleland**
While working on a project using Slim + Twig, I've run into a use case where I want to use Twig's ability to traverse multiple template directories to load and render a template.

This pull request adds a public static property called `$twigTemplateDirs` to the `\Slim\Extras\Views\Twig.php` file that allows a user to set an array of directories for Twig to use. If this array is empty, it falls back to the current behavior of using the parent class' `getTemplatesDirectory()` method.

I also added documentation for all the available public static properties on the Twig view class.

If there's a smarter way to do this in Slim or just an option/feature I'm missing in Slim itself let me know. Thanks!

### CODE REVIEW

**Comment by silentworks** [comment]
This is great @richleland can you make this backward compatible and send the pull request to the develop branch instead. The reason for backward compatibility if for those who have already implemented Twig into their project, we don't want to break that upon upgrade.

I will be changing these methods from static interface to being a singleton in the future. At that point we can remove any backward compatibility.

**Comment by richleland** [comment]
Hi @silentworks I think it's already backward combatible:
`https://github.com/codeguy/Slim-Extras/pull/42/files#L1R81`

That falls back to the original behavior and `$twigTemplateDirs` is an empty array by default. Is there another way you think the backwards compat should be handled?

**Comment by richleland** [comment]
Github auto-changed that link I put in so I turned it into a code block! :panda_face:

**Comment by silentworks** [comment]
@richleland correct you are indeed, sorry I didn't look through the entire code. Can you change the pull request to point to develop branch instead. I need to test after merging, so wouldn't want to be testing on master branch.

**Comment by richleland** [comment]
Closing in favor of #43, which is a pull request into the develop branch.

**Pull request closed without merging**
