### PR TITLE
Expose Slim::urlFor function to Twig templates

### PR DESCRIPTION
**Pull request by ziadoz**
I find this pretty handy when building my templates.

### CODE REVIEW

**Comment by silentworks** [comment]
This would man adding in a single function to the actual TwigView class which wouldn't be that helpful. While Josh decide on how he will implement all of Slim core functions into Twig you can easily achieve this without adding function to that class by doing.

```
$twig_env = $twig->getEnvironment();
$twig_env->addFunction('url', new Twig_Function_Function('Slim::urlFor'));
```

I went about doing it in a different way since I wanted to get all slim related functions in my Twig views.

```
$twig_env->addGlobal('slim', $app);
```

There are various ways without making changes to the TwigView class.

**Comment by ziadoz** [comment]
I thought this repository was no longer maintained, so I'm glad to see it's been picked up again.

The reason I made this pull request is because it makes sense to be able to generate the URLs for Slim named routes inside view templates. I think making this part of the `TwigView` class would be preferable to making people do it in their own code as it's a common use case in my experience (and a simple addition). Exposing all of Slims functions to Twig seems like a bad alternative to me as many of it's methods have no place being available in the view.

**Comment by silentworks** [comment]
I am currently working on a better way to implement some of Slim view related functions into the template parsers, this way it will be easier to maintain for future versions of Slim. I am working on the Twig version first and then I will move on to the others. Just so you know, your function you propose wouldn't work on the current version of Slim since urlFor is no longer a static function.

**Comment by silentworks** [comment]
This has now been implemented in the latest version of the repo, I have opted to make Extensions external and not written directly inside of the TwigView class, this allows for more flexibility as an application grows.

**Pull request closed without merging**
